print("Hello, World!")
print("Welcome to the world of programming!")
print("This is a simple Python program.")
print("You can run this code to see the output.")
print("Feel free to modify the code and experiment with it.")
print("Happy coding!")